build:
    stage: build
    image: ubuntu:18.04
    script:
      - sh ./compile.sh
    artifacts:
      paths:
        - bin/ffplay
        - bin/ffprobe
        - bin/ffmpeg
        - ffmpeg_sources/ffmpeg-4.1.3/ffbuild/config.log

# release:
#   release_job:
#     stage: release
#     image: registry.gitlab.com/gitlab-org/release-cli:latest
#     script:
#       - echo 'Release ffmpeg'
#     release:
#         tag_name: ffmpeg-ndi-4.3
#         description: 'FFMPEG NDI'
          