stages:
  - build
  - release

build:
  stage: build
  image: ubuntu:18.04
  script:
    - sh ./compile.sh
  artifacts:
    paths:
      - bin/ffplay
      - bin/ffprobe
      - bin/ffmpeg
      - ffmpeg_sources/ffmpeg-4.1.3/ffbuild/config.log
