build:
    stage: build
    image: ubuntu:18.04
    script:
      - sh ./compile.sh
    artifacts:
      paths:
        - ./ffmpeg_build/bin/ffplay
        - ./ffmpeg_build/bin/ffprobe
        - ./ffmpeg_build/bin/ffmpeg

# release:
#   release_job:
#     stage: release
#     image: registry.gitlab.com/gitlab-org/release-cli:latest
#     script:
#       - echo 'Release ffmpeg'
#     release:
#         tag_name: ffmpeg-ndi-4.3
#         description: 'FFMPEG NDI'
          